module.exports = {
    searchField: '#js-site-search-input',
    searchResults: '#js-hits',
    productItemTitle: '.alk-icon-carrito-plus',
    productInCart: '.item-column',
    buyNowButton: '#addToCartButton',
    emailField: '#j_username',
    continueToCheckout: '#alkostoSoftLoginForm button',
    goToCartButton: '.cart-pop-up-warrantyFooter_cartRedirect',
    productCheckout: '#js-go-to-pay',
    deliveryMethodButton: '#deliveryMethodSubmit',
    continuePaymentPse: '[data-pmcode="PSE"]',
    selectBank: '.roform-group',
    listOfOptions: '.float-select--list',
    selectDocument: '[data-value="CC"]',
    selectClientType: '.payment-method-pse__client-type',
    selectTypeOfDocument: '.payment-method-pse__identification--type',
    documentField: '#documentId',
    continueOfMethodPayment: '.js-changeDocumentIdDigitalPayments',
    totalAmount: '.grand-total',
    payNowButton: '#placeOrder',
    payNowButtonMobile: '#placeOrderForm2 #placeOrder',
    firstNameInput: '#firstName',
    lastNameInput: '#lastName',
    phoneInput: '#phone',
    authorizeTerms: '.form-check-label',
    createUserButton: '#js-buttonSignIn',
    addressIdTypeDocument: '.addressId__type',
    addressIdDocument: '[name="idNumber"]',
    departmentField: '.checkout-shipping_address .js-addressForm-input',
    addressInput: '#addressLine1',
    addressDistrict: '#addressDistrict',
    continueAddressButton: '#continueAddress',
    confirmSelectAddress: '.js-new-address-select .custom-radio__label',
    confirmAddressButon: '.checkoutAddressSuggestion__btn_SuggestedConfirm',
    countProducts: '.js-cart-items-count',
}